export { default as authController } from './auth.controller.js';
export { default as adminController } from './admin.controller.js';
export { default as doctorController } from './doctor.controller.js';
export { default as patientController } from './patient.controller.js';
export { default as appointmentController } from './appointment.controller.js';
export { default as prescriptionController } from './prescription.controller.js';
export { default as consultationController } from './consultation.controller.js';
export { default as reportController } from './report.controller.js';
export { default as notificationController } from './notification.controller.js';
